### PR TITLE
Option to specify a source address for nfreplay

### PR DESCRIPTION
**Pull request by borjam**
Added the option **-S sourceaddress** to nfreplay in order to specify an optional source address for Netflow export.

### CODE REVIEW

**Review by phaag — CHANGES_REQUESTED** [review]
the patch is not based on the current master branch and removes changes. Please make sure  to use the latest version.

**Comment by borjam** [comment]
> the patch is not based on the current master branch and removes changes. Please make sure to use the latest version.

My apologies! Corrected now I think.

**Comment by phaag** [comment]
Hmm .. it looks like that `73bf02e` is a diff of two different states of the master branch and `df770f9` a diff of nfreplay but without the source address patch. Maybe it's easier, I implement it by myself - it's not a big issue.

**Comment by borjam** [comment]
> On 6 Feb 2023, at 15:21, Peter Haag ***@***.***> wrote:
> 
> 
> Hmm .. it looks like that 73bf02e is a diff of two different states of the master branch and df770f9 a diff of nfreplay but without the source address patch. Maybe it's easier, I implement it by myself - it's not a big issue.

I must admit I am really dumb with Git. 

I made sure that the only changes applied to nfreplay.c (on which we collided, I had mistakenly destroyed your version.h related stuff) 
are the ones I made.

I will check again!

Sorry for the inconvenience!!



Borja.

**Pull request closed without merging**
